name: run_all_tests

on: [push, pull_request, workflow_dispatch]

jobs:
  RunAllTests:
    runs-on: ubuntu-20.04
    container: python:3.9.7
    steps:
      - uses: actions/checkout@v2
      - name: run_all_tests
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          python -m pytest